-- MySQL Script generated by MySQL Workbench
-- Fri Apr 20 14:44:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proxibanquev3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proxibanquev3` ;

-- -----------------------------------------------------
-- Schema proxibanquev3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proxibanquev3` DEFAULT CHARACTER SET utf8 ;
USE `proxibanquev3` ;

-- -----------------------------------------------------
-- Table `proxibanquev3`.`conseiller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proxibanquev3`.`conseiller` ;

CREATE TABLE IF NOT EXISTS `proxibanquev3`.`conseiller` (
  `idconseiller` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idconseiller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxibanquev3`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proxibanquev3`.`client` ;

CREATE TABLE IF NOT EXISTS `proxibanquev3`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `codePostal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `idConseiller` INT NULL,
  `clientcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient`),
  INDEX `idConseiller_idx` (`idConseiller` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxibanquev3`.`compteCourant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proxibanquev3`.`compteCourant` ;

CREATE TABLE IF NOT EXISTS `proxibanquev3`.`compteCourant` (
  `numeroCompte` INT NOT NULL,
  `solde` FLOAT NULL,
  `decouverAutorise` FLOAT NULL,
  `idClient` INT NULL,
  `typeCompte` INT NULL,
  PRIMARY KEY (`numeroCompte`),
  INDEX `idClient_idx` (`idClient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxibanquev3`.`compteEpargne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proxibanquev3`.`compteEpargne` ;

CREATE TABLE IF NOT EXISTS `proxibanquev3`.`compteEpargne` (
  `numeroCompte` INT NOT NULL,
  `solde` FLOAT NULL,
  `tauxRemuneration` FLOAT NULL,
  `typeCompte` INT NULL,
  `idClient` INT NULL,
  PRIMARY KEY (`numeroCompte`),
  INDEX `idClient_idx` (`idClient` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
